---

services:

  es:
    container_name: tla-es
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
      discovery.type: single-node
      xpack.security.enabled: "false"
      ingest.geoip.downloader.enabled: "false"
    ports:
      - ${ES_PORT:-9200}:9200
    restart: unless-stopped

  e2e:
    container_name: e2e
    image: cypress/included:14.5.2
    working_dir: /e2e
    volumes:
      - ./src/test/e2e:/e2e
    environment:
      - CYPRESS_VIDEO
      - CYPRESS_BASE_URL
    network_mode: host
    tty: true

...
