---

services:

  e2e:
    container_name: e2e
    image: cypress/included:14.2.1
    working_dir: /e2e
    volumes:
      - ./src/test/e2e:/e2e
    environment:
      - CYPRESS_VIDEO
      - CYPRESS_BASE_URL
    network_mode: host
    tty: true

...
